In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
np.zeros(10, dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [9]:
np.zeros(10, dtype = 'int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [18]:
x1 = np.random.randint(10, size = (2,4))
x1

array([[0, 2, 6, 7],
       [8, 1, 3, 5]])

In [19]:
x1.ndim

2

In [20]:
x1.size

8

In [21]:
x1.shape

(2, 4)

In [24]:
x1[:2, ::2]

array([[0, 6],
       [8, 3]])

In [28]:
x1[0,]

array([0, 2, 6, 7])

In [30]:
x1[0]

array([0, 2, 6, 7])

In [33]:
x2 = x1[:2,:2]
x2

array([[0, 2],
       [8, 1]])

In [36]:
x2[0,0] = 999
x1

array([[999,   2,   6,   7],
       [  8,   1,   3,   5]])

In [43]:
x3 = x2[:2, :2].copy()
x3[0] = 0
x2

array([[999,   2],
       [  8,   1]])

In [45]:
x = np.array([1,2,3])
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [52]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
upper, lower = np.vsplit(grid, [2])
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])